language: php
jobs:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.3
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 7.4
    - php: 7.4
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 8.0
    - php: 8.0
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: nightly
      env: COMPOSER_OPTIONS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update "php-coveralls/php-coveralls:^1 | ^2"
  - travis_retry composer update --no-interaction --prefer-dist --no-progress --no-suggest $COMPOSER_OPTIONS
  - if [ -f vendor/bin/coveralls ]; then ln -s coveralls vendor/bin/php-coveralls; fi

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpcs src tests --standard=psr2 -sp
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls