language: php
os: linux
dist: bionic
php:
  - 7.3
  - 7.4
  - 8.0
before_script:
  - mkdir -p build/logs
  - composer install

jobs:
  include:
    - php: nightly
      env: COMPOSER_OPTIONS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpcs src tests --standard=psr12 -sp
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls